<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;

class ProductSeeder extends Seeder
{
    public function run()
    {
         $products = [
            [
                'id' => 1,
                'name' => 'Apples',
                'slug' => 'apples',
                'description' => 'An apple is a sweet, edible fruit produced by an apple tree (Malus domestica). Apple trees are ... The skin of ripe apples is generally red, yellow, green, pink, or russetted, though many bi- or tri-colored cultivars may be found.',
                'type_id' => 1,
                'price' => 2.00,
                'shop_id' => 6,
                'sale_price' => 1.60,
                'min_price' => 2.00,
                'max_price' => 2.00,
                'sku' => '1',
                'quantity' => 18,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1lb',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([
                    ['id' => '573', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/572/apple-1.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/572/conversions/apple-1-thumbnail.jpg'],
                    ['id' => '574', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/573/apple-2.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/573/conversions/apple-2-thumbnail.jpg']
                ]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => '2021-03-08 10:24:53',
                'updated_at' => '2021-12-23 18:16:06'
            ],
            [
                'id' => 2,
                'name' => 'Baby Spinach',
                'slug' => 'baby-spinach',
                'description' => 'Spinach (Spinacia oleracea) is a leafy green flowering plant native to central and western Asia. It is of the order Caryophyllales, family Amaranthaceae, subfamily Chenopodioideae. Its leaves are a common edible vegetable consumed either fresh.',
                'type_id' => 1,
                'price' => 0.60,
                'shop_id' => 6,
                'sale_price' => null,
                'min_price' => 0.60,
                'max_price' => 0.60,
                'sku' => '2',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '2lb',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '2', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/2/BabySpinach.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/2/conversions/BabySpinach-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([
                    ['id' => '576', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/575/baby-spinach-1.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/575/conversions/baby-spinach-1-thumbnail.jpg'],
                    ['id' => '577', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/576/baby-spinach-2.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/576/conversions/baby-spinach-2-thumbnail.jpg']
                ]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => '2021-03-08 10:26:13',
                'updated_at' => '2021-12-23 18:16:03'
            ],
            [
                'id' => 3,
                'name' => 'Blueberries',
                'slug' => 'blueberries',
                'description' => 'Blueberries are perennial flowering plants with blue or purple berries. They are classified in the section Cyanococcus within the genus Vaccinium. Vaccinium also includes cranberries, bilberries, huckleberries and Madeira blueberries. Commercial blueberries—both wild and cultivated —are all native to North America.',
                'type_id' => 1,
                'price' => 3.00,
                'shop_id' => 6,
                'sale_price' => null,
                'min_price' => 3.00,
                'max_price' => 3.00,
                'sku' => '3',
                'quantity' => 30,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1lb',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '3', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/3/blueberries.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/3/conversions/blueberries-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([
                    ['id' => '580', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/579/Bluberries-2.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/579/conversions/Bluberries-2-thumbnail.jpg'],
                    ['id' => '581', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/580/Bluberries.png', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/580/conversions/Bluberries-thumbnail.jpg']
                ]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => '2021-03-08 10:40:00',
                'updated_at' => '2021-12-23 18:16:00'
            ],
            [
                'id' => 899,
                'name' => 'Product 899',
                'slug' => 'product-899',
                'description' => 'Description for product 899',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '899',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 4,
                'name' => 'Product 4',
                'slug' => 'product-4',
                'description' => 'Description for product 4',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '4',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 5,
                'name' => 'Product 5',
                'slug' => 'product-5',
                'description' => 'Description for product 5',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '5',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 6,
                'name' => 'Product 6',
                'slug' => 'product-6',
                'description' => 'Description for product 6',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '6',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 21,
                'name' => 'Product 21',
                'slug' => 'product-21',
                'description' => 'Description for product 21',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '21',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 43,
                'name' => 'Product 43',
                'slug' => 'product-43',
                'description' => 'Description for product 43',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '43',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 65,
                'name' => 'Product 65',
                'slug' => 'product-65',
                'description' => 'Description for product 65',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '65',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 102,
                'name' => 'Product 102',
                'slug' => 'product-102',
                'description' => 'Description for product 102',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '102',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 110,
                'name' => 'Product 110',
                'slug' => 'product-110',
                'description' => 'Description for product 110',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '110',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 412,
                'name' => 'Product 412',
                'slug' => 'product-412',
                'description' => 'Description for product 412',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '412',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 467,
                'name' => 'Product 467',
                'slug' => 'product-467',
                'description' => 'Description for product 467',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '467',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 888,
                'name' => 'Product 888',
                'slug' => 'product-888',
                'description' => 'Description for product 888',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '888',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 891,
                'name' => 'Product 891',
                'slug' => 'product-891',
                'description' => 'Description for product 891',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '891',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 883,
                'name' => 'Product 883',
                'slug' => 'product-883',
                'description' => 'Description for product 883',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '883',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 884,
                'name' => 'Product 884',
                'slug' => 'product-884',
                'description' => 'Description for product 884',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '884',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 885,
                'name' => 'Product 885',
                'slug' => 'product-885',
                'description' => 'Description for product 885',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '885',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 173,
                'name' => 'Product 173',
                'slug' => 'product-173',
                'description' => 'Description for product 173',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '173',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 946,
                'name' => 'Product 946',
                'slug' => 'product-946',
                'description' => 'Description for product 946',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '946',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'id' => 943,
                'name' => 'Product 943',
                'slug' => 'product-943',
                'description' => 'Description for product 943',
                'type_id' => 1,
                'price' => 10.00,
                'shop_id' => 1,
                'sale_price' => null,
                'min_price' => 10.00,
                'max_price' => 10.00,
                'sku' => '943',
                'quantity' => 10,
                'in_stock' => true,
                'is_taxable' => false,
                'shipping_class_id' => null,
                'status' => 'publish',
                'product_type' => 'simple',
                'unit' => '1pc',
                'height' => null,
                'width' => null,
                'length' => null,
                'image' => json_encode(['id' => '1', 'original' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/Apples.jpg', 'thumbnail' => 'https://pickbazarlaravel.s3.ap-southeast-1.amazonaws.com/1/conversions/Apples-thumbnail.jpg']),
                'video' => null,
                'gallery' => json_encode([]),
                'author_id' => null,
                'manufacturer_id' => null,
                'is_digital' => false,
                'is_external' => false,
                'external_product_url' => null,
                'external_product_button_text' => null,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        $localPath = public_path('assets/uploads/products');
        if (!file_exists($localPath)) {
            mkdir($localPath, 0755, true);
        }

        foreach ($products as &$product) {
            // ✅ ডাউনলোড প্রাইমারি image
            $remoteUrl = $product['image'];
            if ($remoteUrl) {
                try {
                    $response = Http::get($remoteUrl);
                    if ($response->successful()) {
                        $filename = basename(parse_url($remoteUrl, PHP_URL_PATH)) ?: Str::uuid() . '.jpg';
                        file_put_contents($localPath . '/' . $filename, $response->body());
                        $product['image'] = 'assets/uploads/products/' . $filename; // local path হিসেবে replace
                    } else {
                        $product['image'] = null;
                    }
                } catch (\Exception $e) {
                    $product['image'] = null;
                }
            }

            // ✅ ডাউনলোড gallery images
            // ✅ ডাউনলোড gallery images
            $gallery = [];
            $galleryItems = is_string($product['gallery']) ? json_decode($product['gallery'], true) : $product['gallery'];

            if (is_array($galleryItems)) {
                foreach ($galleryItems as $img) {
                    $remoteUrl = $img['original'] ?? null;
                    if ($remoteUrl) {
                        try {
                            $response = Http::get($remoteUrl);
                            if ($response->successful()) {
                                $filename = basename(parse_url($remoteUrl, PHP_URL_PATH)) ?: Str::uuid() . '.jpg';
                                file_put_contents($localPath . '/' . $filename, $response->body());

                                $thumbnailUrl = $img['thumbnail'] ?? $remoteUrl;
                                $thumbFilename = basename(parse_url($thumbnailUrl, PHP_URL_PATH)) ?: Str::uuid() . '-thumb.jpg';
                                file_put_contents($localPath . '/' . $thumbFilename, Http::get($thumbnailUrl)->body());

                                $gallery[] = [
                                    'id' => $img['id'],
                                    'original' => 'assets/uploads/products/' . $filename,
                                    'thumbnail' => 'assets/uploads/products/' . $thumbFilename,
                                ];
                            }
                        } catch (\Exception $e) {
                            // ignore
                        }
                    }
                }
            }

            $product['gallery'] = json_encode($gallery); // JSON column
        }

        // ✅ Insert into DB
        try {
            DB::table('products')->insert($products);
            echo "🎉 Products seeded successfully!\n";
        } catch (\Exception $e) {
            echo "❌ Database error: " . $e->getMessage() . "\n";
        }
    }
}
